/* eslint-disable */
/* prettier-ignore */
// oxfmt-ignore
// @ts-nocheck
// noinspection ES6UnusedImports
// Generated by vue-router. !! DO NOT MODIFY THIS FILE !!
// It's recommended to commit this file.
// Make sure to add this file to your tsconfig.json file as an "includes" or "files" entry.

import type {
  RouteRecordInfo,
  ParamValue,
  ParamValueOneOrMore,
  ParamValueZeroOrMore,
  ParamValueZeroOrOne,
} from 'vue-router'
import type {
  _ExtractParamParserType,
} from 'vue-router/experimental'

declare module 'vue-router' {
  interface TypesConfig {
    _ParamParsers: {}
    RouteNamedMap: import('vue-router/auto-routes').RouteNamedMap
    _RouteFileInfoMap: import('vue-router/auto-routes')._RouteFileInfoMap
  }
}

declare module 'vue-router/auto-routes' {
  /**
   * Route name map generated by vue-router
   */
  export interface RouteNamedMap {
    '/(admin)': RouteRecordInfo<
      '/(admin)',
      '/',
      Record<never, never>,
      Record<never, never>,
      | '/(admin)/'
      | '/(admin)/approvals'
      | '/(admin)/calendar'
      | '/(admin)/commerce'
      | '/(admin)/commerce/after-sales'
      | '/(admin)/commerce/orders'
      | '/(admin)/commerce/products'
      | '/(admin)/crm'
      | '/(admin)/crm/customers'
      | '/(admin)/customer/[id]'
      | '/(admin)/data'
      | '/(admin)/data/analytics'
      | '/(admin)/notifications'
      | '/(admin)/order/[id]'
      | '/(admin)/profile'
      | '/(admin)/projects'
      | '/(admin)/system'
      | '/(admin)/system/logs'
      | '/(admin)/system/menus'
      | '/(admin)/system/roles'
      | '/(admin)/system/settings'
      | '/(admin)/system/users'
      | '/(admin)/tasks'
    >,
    '/(admin)/': RouteRecordInfo<
      '/(admin)/',
      '/',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/(admin)/approvals': RouteRecordInfo<
      '/(admin)/approvals',
      '/approvals',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/(admin)/calendar': RouteRecordInfo<
      '/(admin)/calendar',
      '/calendar',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/(admin)/commerce': RouteRecordInfo<
      '/(admin)/commerce',
      '/commerce',
      Record<never, never>,
      Record<never, never>,
      | '/(admin)/commerce/after-sales'
      | '/(admin)/commerce/orders'
      | '/(admin)/commerce/products'
    >,
    '/(admin)/commerce/after-sales': RouteRecordInfo<
      '/(admin)/commerce/after-sales',
      '/commerce/after-sales',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/(admin)/commerce/orders': RouteRecordInfo<
      '/(admin)/commerce/orders',
      '/commerce/orders',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/(admin)/commerce/products': RouteRecordInfo<
      '/(admin)/commerce/products',
      '/commerce/products',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/(admin)/crm': RouteRecordInfo<
      '/(admin)/crm',
      '/crm',
      Record<never, never>,
      Record<never, never>,
      | '/(admin)/crm/customers'
    >,
    '/(admin)/crm/customers': RouteRecordInfo<
      '/(admin)/crm/customers',
      '/crm/customers',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/(admin)/customer/[id]': RouteRecordInfo<
      '/(admin)/customer/[id]',
      '/customer/:id',
      { id: ParamValue<true> },
      { id: ParamValue<false> },
      | never
    >,
    '/(admin)/data': RouteRecordInfo<
      '/(admin)/data',
      '/data',
      Record<never, never>,
      Record<never, never>,
      | '/(admin)/data/analytics'
    >,
    '/(admin)/data/analytics': RouteRecordInfo<
      '/(admin)/data/analytics',
      '/data/analytics',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/(admin)/notifications': RouteRecordInfo<
      '/(admin)/notifications',
      '/notifications',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/(admin)/order/[id]': RouteRecordInfo<
      '/(admin)/order/[id]',
      '/order/:id',
      { id: ParamValue<true> },
      { id: ParamValue<false> },
      | never
    >,
    '/(admin)/profile': RouteRecordInfo<
      '/(admin)/profile',
      '/profile',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/(admin)/projects': RouteRecordInfo<
      '/(admin)/projects',
      '/projects',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/(admin)/system': RouteRecordInfo<
      '/(admin)/system',
      '/system',
      Record<never, never>,
      Record<never, never>,
      | '/(admin)/system/logs'
      | '/(admin)/system/menus'
      | '/(admin)/system/roles'
      | '/(admin)/system/settings'
      | '/(admin)/system/users'
    >,
    '/(admin)/system/logs': RouteRecordInfo<
      '/(admin)/system/logs',
      '/system/logs',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/(admin)/system/menus': RouteRecordInfo<
      '/(admin)/system/menus',
      '/system/menus',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/(admin)/system/roles': RouteRecordInfo<
      '/(admin)/system/roles',
      '/system/roles',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/(admin)/system/settings': RouteRecordInfo<
      '/(admin)/system/settings',
      '/system/settings',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/(admin)/system/users': RouteRecordInfo<
      '/(admin)/system/users',
      '/system/users',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/(admin)/tasks': RouteRecordInfo<
      '/(admin)/tasks',
      '/tasks',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/account/login': RouteRecordInfo<
      '/account/login',
      '/account/login',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/account/logout': RouteRecordInfo<
      '/account/logout',
      '/account/logout',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/error/403': RouteRecordInfo<
      '/error/403',
      '/error/403',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/error/404': RouteRecordInfo<
      '/error/404',
      '/error/404',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/error/500': RouteRecordInfo<
      '/error/500',
      '/error/500',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
  }

  /**
   * Route file to route info map by vue-router.
   * Used by the \`sfc-typed-router\` Volar plugin to automatically type \`useRoute()\`.
   *
   * Each key is a file path relative to the project root with 2 properties:
   * - routes: union of route names of the possible routes when in this page (passed to useRoute<...>())
   * - views: names of nested views (can be passed to <RouterView name="...">)
   *
   * @internal
   */
  export interface _RouteFileInfoMap {
    'src/pages/(admin).vue': {
      routes:
        | '/(admin)'
        | '/(admin)/'
        | '/(admin)/approvals'
        | '/(admin)/calendar'
        | '/(admin)/commerce'
        | '/(admin)/commerce/after-sales'
        | '/(admin)/commerce/orders'
        | '/(admin)/commerce/products'
        | '/(admin)/crm'
        | '/(admin)/crm/customers'
        | '/(admin)/customer/[id]'
        | '/(admin)/data'
        | '/(admin)/data/analytics'
        | '/(admin)/notifications'
        | '/(admin)/order/[id]'
        | '/(admin)/profile'
        | '/(admin)/projects'
        | '/(admin)/system'
        | '/(admin)/system/logs'
        | '/(admin)/system/menus'
        | '/(admin)/system/roles'
        | '/(admin)/system/settings'
        | '/(admin)/system/users'
        | '/(admin)/tasks'
      views:
        | 'default'
      pathParamNames:
        | never
    }
    'src/pages/(admin)/index.vue': {
      routes:
        | '/(admin)/'
      views:
        | never
      pathParamNames:
        | never
    }
    'src/pages/(admin)/approvals.vue': {
      routes:
        | '/(admin)/approvals'
      views:
        | never
      pathParamNames:
        | never
    }
    'src/pages/(admin)/calendar.vue': {
      routes:
        | '/(admin)/calendar'
      views:
        | never
      pathParamNames:
        | never
    }
    'src/pages/(admin)/commerce.vue': {
      routes:
        | '/(admin)/commerce'
        | '/(admin)/commerce/after-sales'
        | '/(admin)/commerce/orders'
        | '/(admin)/commerce/products'
      views:
        | 'default'
      pathParamNames:
        | never
    }
    'src/pages/(admin)/commerce/after-sales.vue': {
      routes:
        | '/(admin)/commerce/after-sales'
      views:
        | never
      pathParamNames:
        | never
    }
    'src/pages/(admin)/commerce/orders.vue': {
      routes:
        | '/(admin)/commerce/orders'
      views:
        | never
      pathParamNames:
        | never
    }
    'src/pages/(admin)/commerce/products.vue': {
      routes:
        | '/(admin)/commerce/products'
      views:
        | never
      pathParamNames:
        | never
    }
    'src/pages/(admin)/crm.vue': {
      routes:
        | '/(admin)/crm'
        | '/(admin)/crm/customers'
      views:
        | 'default'
      pathParamNames:
        | never
    }
    'src/pages/(admin)/crm/customers.vue': {
      routes:
        | '/(admin)/crm/customers'
      views:
        | never
      pathParamNames:
        | never
    }
    'src/pages/(admin)/customer/[id].vue': {
      routes:
        | '/(admin)/customer/[id]'
      views:
        | never
      pathParamNames:
        | 'id'
    }
    'src/pages/(admin)/data.vue': {
      routes:
        | '/(admin)/data'
        | '/(admin)/data/analytics'
      views:
        | 'default'
      pathParamNames:
        | never
    }
    'src/pages/(admin)/data/analytics.vue': {
      routes:
        | '/(admin)/data/analytics'
      views:
        | never
      pathParamNames:
        | never
    }
    'src/pages/(admin)/notifications.vue': {
      routes:
        | '/(admin)/notifications'
      views:
        | never
      pathParamNames:
        | never
    }
    'src/pages/(admin)/order/[id].vue': {
      routes:
        | '/(admin)/order/[id]'
      views:
        | never
      pathParamNames:
        | 'id'
    }
    'src/pages/(admin)/profile.vue': {
      routes:
        | '/(admin)/profile'
      views:
        | never
      pathParamNames:
        | never
    }
    'src/pages/(admin)/projects.vue': {
      routes:
        | '/(admin)/projects'
      views:
        | never
      pathParamNames:
        | never
    }
    'src/pages/(admin)/system.vue': {
      routes:
        | '/(admin)/system'
        | '/(admin)/system/logs'
        | '/(admin)/system/menus'
        | '/(admin)/system/roles'
        | '/(admin)/system/settings'
        | '/(admin)/system/users'
      views:
        | 'default'
      pathParamNames:
        | never
    }
    'src/pages/(admin)/system/logs.vue': {
      routes:
        | '/(admin)/system/logs'
      views:
        | never
      pathParamNames:
        | never
    }
    'src/pages/(admin)/system/menus.vue': {
      routes:
        | '/(admin)/system/menus'
      views:
        | never
      pathParamNames:
        | never
    }
    'src/pages/(admin)/system/roles.vue': {
      routes:
        | '/(admin)/system/roles'
      views:
        | never
      pathParamNames:
        | never
    }
    'src/pages/(admin)/system/settings.vue': {
      routes:
        | '/(admin)/system/settings'
      views:
        | never
      pathParamNames:
        | never
    }
    'src/pages/(admin)/system/users.vue': {
      routes:
        | '/(admin)/system/users'
      views:
        | never
      pathParamNames:
        | never
    }
    'src/pages/(admin)/tasks.vue': {
      routes:
        | '/(admin)/tasks'
      views:
        | never
      pathParamNames:
        | never
    }
    'src/pages/account/login.vue': {
      routes:
        | '/account/login'
      views:
        | never
      pathParamNames:
        | never
    }
    'src/pages/account/logout.vue': {
      routes:
        | '/account/logout'
      views:
        | never
      pathParamNames:
        | never
    }
    'src/pages/error/403.vue': {
      routes:
        | '/error/403'
      views:
        | never
      pathParamNames:
        | never
    }
    'src/pages/error/404.vue': {
      routes:
        | '/error/404'
      views:
        | never
      pathParamNames:
        | never
    }
    'src/pages/error/500.vue': {
      routes:
        | '/error/500'
      views:
        | never
      pathParamNames:
        | never
    }
  }

  /**
   * Get a union of possible route names in a certain route component file.
   * Used by the \`sfc-typed-router\` Volar plugin to automatically type \`useRoute()\`.
   *
   * @internal
   */
  export type _RouteNamesForFilePath<FilePath extends string> =
    _RouteFileInfoMap extends Record<FilePath, infer Info>
      ? Info['routes']
      : keyof RouteNamedMap
}

export {}
