/* eslint-disable */
/* prettier-ignore */
// oxfmt-ignore
// @ts-nocheck
// noinspection ES6UnusedImports
// Generated by vue-router. !! DO NOT MODIFY THIS FILE !!
// It's recommended to commit this file.
// Make sure to add this file to your tsconfig.json file as an "includes" or "files" entry.

import type {
  RouteRecordInfo,
  ParamValue,
  ParamValueOneOrMore,
  ParamValueZeroOrMore,
  ParamValueZeroOrOne,
} from 'vue-router'
import type {
  _ExtractParamParserType,
} from 'vue-router/experimental'

declare module 'vue-router' {
  interface TypesConfig {
    _ParamParsers: {}
    RouteNamedMap: import('vue-router/auto-routes').RouteNamedMap
    _RouteFileInfoMap: import('vue-router/auto-routes')._RouteFileInfoMap
  }
}

declare module 'vue-router/auto-routes' {
  /**
   * Route name map generated by vue-router
   */
  export interface RouteNamedMap {
    '/(admin)': RouteRecordInfo<
      '/(admin)',
      '/',
      Record<never, never>,
      Record<never, never>,
      | '/(admin)/'
      | '/(admin)/commerce'
      | '/(admin)/commerce/orders'
      | '/(admin)/system'
      | '/(admin)/system/users'
    >,
    '/(admin)/': RouteRecordInfo<
      '/(admin)/',
      '/',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/(admin)/commerce': RouteRecordInfo<
      '/(admin)/commerce',
      '/commerce',
      Record<never, never>,
      Record<never, never>,
      | '/(admin)/commerce/orders'
    >,
    '/(admin)/commerce/orders': RouteRecordInfo<
      '/(admin)/commerce/orders',
      '/commerce/orders',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/(admin)/system': RouteRecordInfo<
      '/(admin)/system',
      '/system',
      Record<never, never>,
      Record<never, never>,
      | '/(admin)/system/users'
    >,
    '/(admin)/system/users': RouteRecordInfo<
      '/(admin)/system/users',
      '/system/users',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/account/login': RouteRecordInfo<
      '/account/login',
      '/account/login',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/account/logout': RouteRecordInfo<
      '/account/logout',
      '/account/logout',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/error/403': RouteRecordInfo<
      '/error/403',
      '/error/403',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/error/404': RouteRecordInfo<
      '/error/404',
      '/error/404',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/error/500': RouteRecordInfo<
      '/error/500',
      '/error/500',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
  }

  /**
   * Route file to route info map by vue-router.
   * Used by the \`sfc-typed-router\` Volar plugin to automatically type \`useRoute()\`.
   *
   * Each key is a file path relative to the project root with 2 properties:
   * - routes: union of route names of the possible routes when in this page (passed to useRoute<...>())
   * - views: names of nested views (can be passed to <RouterView name="...">)
   *
   * @internal
   */
  export interface _RouteFileInfoMap {
    'src/pages/(admin).vue': {
      routes:
        | '/(admin)'
        | '/(admin)/'
        | '/(admin)/commerce'
        | '/(admin)/commerce/orders'
        | '/(admin)/system'
        | '/(admin)/system/users'
      views:
        | 'default'
      pathParamNames:
        | never
    }
    'src/pages/(admin)/index.vue': {
      routes:
        | '/(admin)/'
      views:
        | never
      pathParamNames:
        | never
    }
    'src/pages/(admin)/commerce.vue': {
      routes:
        | '/(admin)/commerce'
        | '/(admin)/commerce/orders'
      views:
        | 'default'
      pathParamNames:
        | never
    }
    'src/pages/(admin)/commerce/orders.vue': {
      routes:
        | '/(admin)/commerce/orders'
      views:
        | never
      pathParamNames:
        | never
    }
    'src/pages/(admin)/system.vue': {
      routes:
        | '/(admin)/system'
        | '/(admin)/system/users'
      views:
        | 'default'
      pathParamNames:
        | never
    }
    'src/pages/(admin)/system/users.vue': {
      routes:
        | '/(admin)/system/users'
      views:
        | never
      pathParamNames:
        | never
    }
    'src/pages/account/login.vue': {
      routes:
        | '/account/login'
      views:
        | never
      pathParamNames:
        | never
    }
    'src/pages/account/logout.vue': {
      routes:
        | '/account/logout'
      views:
        | never
      pathParamNames:
        | never
    }
    'src/pages/error/403.vue': {
      routes:
        | '/error/403'
      views:
        | never
      pathParamNames:
        | never
    }
    'src/pages/error/404.vue': {
      routes:
        | '/error/404'
      views:
        | never
      pathParamNames:
        | never
    }
    'src/pages/error/500.vue': {
      routes:
        | '/error/500'
      views:
        | never
      pathParamNames:
        | never
    }
  }

  /**
   * Get a union of possible route names in a certain route component file.
   * Used by the \`sfc-typed-router\` Volar plugin to automatically type \`useRoute()\`.
   *
   * @internal
   */
  export type _RouteNamesForFilePath<FilePath extends string> =
    _RouteFileInfoMap extends Record<FilePath, infer Info>
      ? Info['routes']
      : keyof RouteNamedMap
}

export {}
